apiVersion: v1
kind: Secret
metadata:
  name: {{ include "compassx.fullname" . }}-secrets
  labels:
    {{- include "compassx.labels" . | nindent 4 }}
type: Opaque
stringData:
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
  secret-key: {{ .Values.secrets.secretKey | quote }}
  catalog-encryption-key: {{ .Values.secrets.catalogEncryptionKey | quote }}
  internal-secret: {{ .Values.secrets.internalSecret | quote }}
  {{- if .Values.postgresql.enabled }}
  pg-password: {{ .Values.postgresql.auth.password | quote }}
  {{- end }}
  {{- if .Values.minio.enabled }}
  minio-root-password: {{ .Values.minio.auth.rootPassword | quote }}
  {{- end }}
