"""Token estimation and context window resolution utility for Agent Watermark Compaction."""

from __future__ import annotations

import json
import logging
from typing import Any

logger = logging.getLogger(__name__)

# Default watermark thresholds (per spec D2, O2, O3)
DEFAULT_HIGH_WATERMARK_RATIO = 0.85  # 85% of active model context window
DEFAULT_LOW_WATERMARK_K = 3          # Keep latest K raw turns
DEFAULT_FALLBACK_CONTEXT_WINDOW = 32_000

# Mapping of known model families / patterns to their context window sizes (in tokens)
MODEL_CONTEXT_WINDOWS: list[tuple[str, int]] = [
    # Gemini models (1M tokens)
    ("gemini-2.5", 1_000_000),
    ("gemini-2.0", 1_000_000),
    ("gemini-1.5", 1_000_000),
    ("gemini", 1_000_000),
    # Anthropic Claude 3 / 3.5 / 3.7 models (200k tokens)
    ("claude-3-7", 200_000),
    ("claude-3-5", 200_000),
    ("claude-3", 200_000),
    ("claude", 200_000),
    # OpenAI models (128k tokens)
    ("gpt-4o-mini", 128_000),
    ("gpt-4o", 128_000),
    ("gpt-4-turbo", 128_000),
    ("o1", 128_000),
    ("o3", 128_000),
    ("o4", 128_000),
    ("gpt-5", 128_000),
    # DeepSeek models (64k tokens)
    ("deepseek-r1", 64_000),
    ("deepseek-reasoner", 64_000),
    ("deepseek-chat", 64_000),
    ("deepseek", 64_000),
    # Open weights & modern OSS LLMs (128k tokens)
    ("llama-3.3", 128_000),
    ("llama-3.2", 128_000),
    ("llama-3.1", 128_000),
    ("qwen2.5", 128_000),
    ("qwen-2.5", 128_000),
    ("mistral-large", 128_000),
    ("mistral-small", 128_000),
    ("codestral", 128_000),
    # Legacy models
    ("gpt-4", 16_384),
    ("gpt-3.5-turbo", 16_384),
]


def resolve_model_context_window(conn: Any | None) -> int:
    """Resolve the token context window for the active LLM connection.

    Checks:
    1. Explicit `conn.config["context_window"]` or `conn.config["max_context_tokens"]` override.
    2. Pattern matching against `conn.model_name`.
    3. Fallback default (32,000 tokens).
    """
    if conn is None:
        return DEFAULT_FALLBACK_CONTEXT_WINDOW

    # 1. Explicit connection config override
    config = getattr(conn, "config", None) or {}
    if isinstance(config, dict):
        custom_window = config.get("context_window") or config.get("max_context_tokens")
        if custom_window:
            try:
                val = int(custom_window)
                if val > 0:
                    return val
            except (ValueError, TypeError):
                pass

    # 2. Known model name matching
    model_name = (getattr(conn, "model_name", None) or "").lower().strip()
    for pattern, window_size in MODEL_CONTEXT_WINDOWS:
        if pattern in model_name:
            return window_size

    return DEFAULT_FALLBACK_CONTEXT_WINDOW


def estimate_text_tokens(text: str | None) -> int:
    """Estimate token count for a text string using standard ~4 chars/token heuristic."""
    if not text:
        return 0
    # Standard approximation: 1 token ≈ 4 characters for English / code / punctuation
    return max(1, (len(text) + 3) // 4)


def estimate_messages_tokens(messages: list[dict[str, Any]]) -> int:
    """Estimate total token count for a list of OpenAI-formatted chat messages.

    Includes role overhead, content text/multimodal structure, tool calls, and tool results.
    """
    total = 0
    for msg in messages:
        # Base per-message framing overhead (~4 tokens per message)
        total += 4

        role = msg.get("role")
        if role:
            total += 1

        content = msg.get("content")
        if isinstance(content, str):
            total += estimate_text_tokens(content)
        elif isinstance(content, list):
            # Multimodal payload parts
            for part in content:
                if isinstance(part, dict):
                    if part.get("type") == "text":
                        total += estimate_text_tokens(part.get("text"))
                    elif part.get("type") == "image_url":
                        # Standard fixed tile estimate for vision tokens (~800 tokens)
                        total += 800
                elif isinstance(part, str):
                    total += estimate_text_tokens(part)

        # Tool calls generated by assistant
        tool_calls = msg.get("tool_calls")
        if isinstance(tool_calls, list):
            for tc in tool_calls:
                total += 10  # tool call structure overhead
                if isinstance(tc, dict):
                    fn = tc.get("function") or {}
                    total += estimate_text_tokens(fn.get("name"))
                    args = fn.get("arguments")
                    if isinstance(args, str):
                        total += estimate_text_tokens(args)
                    elif isinstance(args, (dict, list)):
                        total += estimate_text_tokens(json.dumps(args))

        # Tool result content
        if role == "tool":
            tool_name = msg.get("name")
            if tool_name:
                total += estimate_text_tokens(tool_name)

    return total
