"""Default seed configuration for Ontology Metamodel and Knowledge Graph (Pure DB Seed)."""

DEFAULT_SEED_TYPES = [
    {
        "id": "org",
        "label": "Org Root",
        "description": "Root platform & organization architecture",
        "shape": "hexagon",
        "base_radius": 30,
        "tier": 0,
        "is_system": True,
    },
    {
        "id": "domain",
        "label": "Domain Chip",
        "description": "Primary architectural functional domains",
        "shape": "chip",
        "base_radius": 17,
        "tier": 1,
        "is_system": True,
    },
    {
        "id": "subdomain",
        "label": "Subdomain Disc",
        "description": "System functional areas and subdomains",
        "shape": "circle",
        "base_radius": 11,
        "tier": 2,
        "is_system": True,
    },
    {
        "id": "element",
        "label": "Element Pad",
        "description": "Atomic components, algorithms & service pads",
        "shape": "pad",
        "base_radius": 7,
        "tier": 3,
        "is_system": True,
    },
]

DEFAULT_SEED_RELATIONS = [
    # Hierarchical containment rules (System Protected)
    {
        "source_type_id": "org",
        "relation_type": "contains",
        "target_type_id": "domain",
        "is_hierarchical": True,
        "is_system": True,
        "description": "Org root contains primary functional domains",
    },
    {
        "source_type_id": "domain",
        "relation_type": "contains",
        "target_type_id": "subdomain",
        "is_hierarchical": True,
        "is_system": True,
        "description": "Domain boundary contains subdomains",
    },
    {
        "source_type_id": "subdomain",
        "relation_type": "contains",
        "target_type_id": "element",
        "is_hierarchical": True,
        "is_system": True,
        "description": "Subdomain contains atomic elements and component pads",
    },
    # Cross-domain & peer dependencies (System Protected)
    {
        "source_type_id": "domain",
        "relation_type": "depends_on",
        "target_type_id": "domain",
        "is_hierarchical": False,
        "is_system": True,
        "description": "Cross-domain architectural dependency",
    },
    {
        "source_type_id": "domain",
        "relation_type": "relates",
        "target_type_id": "domain",
        "is_hierarchical": False,
        "is_system": True,
        "description": "General domain association",
    },
    {
        "source_type_id": "subdomain",
        "relation_type": "depends_on",
        "target_type_id": "subdomain",
        "is_hierarchical": False,
        "is_system": True,
        "description": "Subdomain depends on another subdomain",
    },
    {
        "source_type_id": "subdomain",
        "relation_type": "relies_on",
        "target_type_id": "subdomain",
        "is_hierarchical": False,
        "is_system": True,
        "description": "Subdomain relies on another subdomain",
    },
    {
        "source_type_id": "subdomain",
        "relation_type": "reads",
        "target_type_id": "subdomain",
        "is_hierarchical": False,
        "is_system": True,
        "description": "Subdomain reads state or events from another subdomain",
    },
    {
        "source_type_id": "subdomain",
        "relation_type": "is_similar_to",
        "target_type_id": "subdomain",
        "is_hierarchical": False,
        "is_system": True,
        "description": "Semantic similarity between subdomains",
    },
    {
        "source_type_id": "subdomain",
        "relation_type": "relates",
        "target_type_id": "subdomain",
        "is_hierarchical": False,
        "is_system": True,
        "description": "General subdomain association",
    },
    {
        "source_type_id": "element",
        "relation_type": "depends_on",
        "target_type_id": "element",
        "is_hierarchical": False,
        "is_system": True,
        "description": "Atomic element dependency",
    },
    {
        "source_type_id": "element",
        "relation_type": "relies_on",
        "target_type_id": "element",
        "is_hierarchical": False,
        "is_system": True,
        "description": "Atomic element reliance",
    },
    {
        "source_type_id": "element",
        "relation_type": "reads",
        "target_type_id": "element",
        "is_hierarchical": False,
        "is_system": True,
        "description": "Atomic element data read",
    },
    {
        "source_type_id": "element",
        "relation_type": "relates",
        "target_type_id": "element",
        "is_hierarchical": False,
        "is_system": True,
        "description": "General element association",
    },
]

DEFAULT_SEED_GRAPH_META = {
    "id": "default",
    "name": "Enterprise Knowledge Graph",
    "version": "1.0.0",
    "description": "Domain-agnostic enterprise architecture meaning layer",
}

DEFAULT_SEED_NODES = [
    # Apex Root Org
    {
        "id": "org/enterprise",
        "kind": "org",
        "title": "Enterprise Organization",
        "description": "Apex organizational entity and systemic governance architecture",
        "parent_id": None,
        "tags": ["organization", "apex", "enterprise"],
        "status": "active",
    },
    # Primary Domains (3)
    {
        "id": "domains/operations",
        "kind": "domain",
        "title": "Operations & Execution",
        "description": "Operational workflows, task dispatching, and service execution",
        "parent_id": "org/enterprise",
        "tags": ["operations", "execution", "workflows"],
        "status": "active",
    },
    {
        "id": "domains/intelligence",
        "kind": "domain",
        "title": "Intelligence & Analytics",
        "description": "Data streaming pipelines, semantic models, and reasoning engines",
        "parent_id": "org/enterprise",
        "tags": ["intelligence", "analytics", "data"],
        "status": "active",
    },
    {
        "id": "domains/infrastructure",
        "kind": "domain",
        "title": "Core Platform & Infrastructure",
        "description": "Foundational identity services, access security, and persistence fabric",
        "parent_id": "org/enterprise",
        "tags": ["infrastructure", "security", "platform"],
        "status": "active",
    },
    # Subdomains (6)
    {
        "id": "subdomains/workflow-engine",
        "kind": "subdomain",
        "title": "Workflow Engine",
        "description": "State progression, queue management, and task dispatching",
        "parent_id": "domains/operations",
        "tags": ["workflow", "engine", "queues"],
        "status": "active",
    },
    {
        "id": "subdomains/service-mesh",
        "kind": "subdomain",
        "title": "Service Mesh",
        "description": "Microservice routing, telemetry routing, and gateway traffic",
        "parent_id": "domains/operations",
        "tags": ["routing", "mesh", "traffic"],
        "status": "active",
    },
    {
        "id": "subdomains/data-pipeline",
        "kind": "subdomain",
        "title": "Data Pipeline",
        "description": "Real-time event streams, batch processing, and schema validation",
        "parent_id": "domains/intelligence",
        "tags": ["pipeline", "etl", "events"],
        "status": "active",
    },
    {
        "id": "subdomains/knowledge-graph",
        "kind": "subdomain",
        "title": "Knowledge Graph",
        "description": "Semantic entity graph, metamodel inference, and ontology mapping",
        "parent_id": "domains/intelligence",
        "tags": ["ontology", "graph", "semantics"],
        "status": "active",
    },
    {
        "id": "subdomains/identity-access",
        "kind": "subdomain",
        "title": "Identity & Access",
        "description": "Authentication, token verification, and role-based access control",
        "parent_id": "domains/infrastructure",
        "tags": ["auth", "security", "iam"],
        "status": "active",
    },
    {
        "id": "subdomains/storage-fabric",
        "kind": "subdomain",
        "title": "Storage Fabric",
        "description": "Relational persistence, object stores, and caching layers",
        "parent_id": "domains/infrastructure",
        "tags": ["database", "storage", "cache"],
        "status": "active",
    },
    # Leaf Elements (12)
    {
        "id": "elements/state-machine",
        "kind": "element",
        "title": "State Machine",
        "description": "Deterministic step executor and retry handler",
        "parent_id": "subdomains/workflow-engine",
        "tags": ["workflow", "engine", "core"],
        "status": "active",
    },
    {
        "id": "elements/job-scheduler",
        "kind": "element",
        "title": "Job Scheduler",
        "description": "Distributed timer triggers and cron scheduling",
        "parent_id": "subdomains/workflow-engine",
        "tags": ["scheduler", "jobs", "dispatch"],
        "status": "active",
    },
    {
        "id": "elements/api-gateway",
        "kind": "element",
        "title": "API Gateway",
        "description": "Ingress reverse-proxy and rate policy enforcement",
        "parent_id": "subdomains/service-mesh",
        "tags": ["gateway", "proxy", "routing"],
        "status": "active",
    },
    {
        "id": "elements/rate-limiter",
        "kind": "element",
        "title": "Rate Limiter",
        "description": "Token bucket and sliding window rate throttling",
        "parent_id": "subdomains/service-mesh",
        "tags": ["security", "throttle", "traffic"],
        "status": "active",
    },
    {
        "id": "elements/event-stream",
        "kind": "element",
        "title": "Event Stream",
        "description": "High-throughput ordered partitioned message bus",
        "parent_id": "subdomains/data-pipeline",
        "tags": ["kafka", "stream", "events"],
        "status": "active",
    },
    {
        "id": "elements/schema-validator",
        "kind": "element",
        "title": "Schema Validator",
        "description": "Real-time payload schema enforcement and type checking",
        "parent_id": "subdomains/data-pipeline",
        "tags": ["schema", "validation", "json"],
        "status": "active",
    },
    {
        "id": "elements/entity-store",
        "kind": "element",
        "title": "Entity Store",
        "description": "Relational and graph entity store for active ontology concepts",
        "parent_id": "subdomains/knowledge-graph",
        "tags": ["ontology", "graph", "storage"],
        "status": "active",
    },
    {
        "id": "elements/inference-engine",
        "kind": "element",
        "title": "Inference Engine",
        "description": "Ontology metamodel inference and rule satisfaction evaluator",
        "parent_id": "subdomains/knowledge-graph",
        "tags": ["ai", "reasoning", "semantic"],
        "status": "active",
    },
    {
        "id": "elements/token-issuer",
        "kind": "element",
        "title": "Token Issuer",
        "description": "Cryptographic JWT / opaque token generator with expiration policies",
        "parent_id": "subdomains/identity-access",
        "tags": ["auth", "jwt", "tokens"],
        "status": "active",
    },
    {
        "id": "elements/audit-logger",
        "kind": "element",
        "title": "Audit Logger",
        "description": "Tamper-evident audit trail for security operations",
        "parent_id": "subdomains/identity-access",
        "tags": ["compliance", "audit", "security"],
        "status": "active",
    },
    {
        "id": "elements/cache-manager",
        "kind": "element",
        "title": "Cache Manager",
        "description": "In-memory caching and eviction policies",
        "parent_id": "subdomains/storage-fabric",
        "tags": ["redis", "cache", "performance"],
        "status": "active",
    },
    {
        "id": "elements/db-pool",
        "kind": "element",
        "title": "DB Connection Pool",
        "description": "Async pooled connections for transactional persistence",
        "parent_id": "subdomains/storage-fabric",
        "tags": ["postgres", "pool", "database"],
        "status": "active",
    },
]

DEFAULT_SEED_EDGES = [
    # Hierarchical containment edges (Org -> Domains)
    {"id": "e_org_ops", "source_id": "org/enterprise", "target_id": "domains/operations", "relation_type": "contains"},
    {"id": "e_org_intel", "source_id": "org/enterprise", "target_id": "domains/intelligence", "relation_type": "contains"},
    {"id": "e_org_infra", "source_id": "org/enterprise", "target_id": "domains/infrastructure", "relation_type": "contains"},

    # Hierarchical containment edges (Domains -> Subdomains)
    {"id": "e_dom_wf", "source_id": "domains/operations", "target_id": "subdomains/workflow-engine", "relation_type": "contains"},
    {"id": "e_dom_mesh", "source_id": "domains/operations", "target_id": "subdomains/service-mesh", "relation_type": "contains"},
    {"id": "e_dom_pipe", "source_id": "domains/intelligence", "target_id": "subdomains/data-pipeline", "relation_type": "contains"},
    {"id": "e_dom_kg", "source_id": "domains/intelligence", "target_id": "subdomains/knowledge-graph", "relation_type": "contains"},
    {"id": "e_dom_iam", "source_id": "domains/infrastructure", "target_id": "subdomains/identity-access", "relation_type": "contains"},
    {"id": "e_dom_store", "source_id": "domains/infrastructure", "target_id": "subdomains/storage-fabric", "relation_type": "contains"},

    # Hierarchical containment edges (Subdomains -> Elements)
    {"id": "e_sub_sm", "source_id": "subdomains/workflow-engine", "target_id": "elements/state-machine", "relation_type": "contains"},
    {"id": "e_sub_sched", "source_id": "subdomains/workflow-engine", "target_id": "elements/job-scheduler", "relation_type": "contains"},
    {"id": "e_sub_gw", "source_id": "subdomains/service-mesh", "target_id": "elements/api-gateway", "relation_type": "contains"},
    {"id": "e_sub_lim", "source_id": "subdomains/service-mesh", "target_id": "elements/rate-limiter", "relation_type": "contains"},
    {"id": "e_sub_stream", "source_id": "subdomains/data-pipeline", "target_id": "elements/event-stream", "relation_type": "contains"},
    {"id": "e_sub_val", "source_id": "subdomains/data-pipeline", "target_id": "elements/schema-validator", "relation_type": "contains"},
    {"id": "e_sub_es", "source_id": "subdomains/knowledge-graph", "target_id": "elements/entity-store", "relation_type": "contains"},
    {"id": "e_sub_infer", "source_id": "subdomains/knowledge-graph", "target_id": "elements/inference-engine", "relation_type": "contains"},
    {"id": "e_sub_tok", "source_id": "subdomains/identity-access", "target_id": "elements/token-issuer", "relation_type": "contains"},
    {"id": "e_sub_audit", "source_id": "subdomains/identity-access", "target_id": "elements/audit-logger", "relation_type": "contains"},
    {"id": "e_sub_cache", "source_id": "subdomains/storage-fabric", "target_id": "elements/cache-manager", "relation_type": "contains"},
    {"id": "e_sub_db", "source_id": "subdomains/storage-fabric", "target_id": "elements/db-pool", "relation_type": "contains"},

    # Cross-subdomain dependencies
    {"id": "e_wf_mesh", "source_id": "subdomains/workflow-engine", "target_id": "subdomains/service-mesh", "relation_type": "depends_on"},
    {"id": "e_kg_pipe", "source_id": "subdomains/knowledge-graph", "target_id": "subdomains/data-pipeline", "relation_type": "reads"},
    {"id": "e_mesh_iam", "source_id": "subdomains/service-mesh", "target_id": "subdomains/identity-access", "relation_type": "depends_on"},
    {"id": "e_kg_store", "source_id": "subdomains/knowledge-graph", "target_id": "subdomains/storage-fabric", "relation_type": "depends_on"},

    # Cross-element dependencies
    {"id": "e_sm_sched", "source_id": "elements/state-machine", "target_id": "elements/job-scheduler", "relation_type": "depends_on"},
    {"id": "e_gw_lim", "source_id": "elements/api-gateway", "target_id": "elements/rate-limiter", "relation_type": "relies_on"},
    {"id": "e_es_stream", "source_id": "elements/entity-store", "target_id": "elements/event-stream", "relation_type": "reads"},
    {"id": "e_gw_tok", "source_id": "elements/api-gateway", "target_id": "elements/token-issuer", "relation_type": "depends_on"},
    {"id": "e_es_db", "source_id": "elements/entity-store", "target_id": "elements/db-pool", "relation_type": "depends_on"},
]
