"""Starter notebook content generator for newly created workspaces."""
from __future__ import annotations

from typing import Any


def build_getting_started_notebook(
    catalog_name: str,
    schema_name: str = "default",
    volume_name: str = "sample_data",
) -> dict[str, Any]:
    """Generate the JSON structure of the getting-started notebook.

    Includes working code references for:
    - Writing and reading files to/from CompassX Volumes (pandas & fsspec)
    - Authoring, locally testing, and promoting AI Agent Tools (@cx.tool)
    - Querying data using DuckDB
    """
    cells = [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# CompassX Platform Reference & Getting Started\n",
                "\n",
                f"Welcome to your workspace! This notebook provides practical code references for core CompassX platform capabilities:\n",
                f"- **Volumes**: Writing and reading files using `cx://` URLs with pandas and `fsspec`\n",
                f"- **AI Agent Tools**: Defining tools with `@cx.tool`, testing locally, and promoting them to the Unified Catalog\n",
                f"- **Tables & SQL**: Creating catalog tables with `cx.write_table` and querying data with `cx.sql`\n",
                "\n",
                f"**Current Catalog Context**: `{catalog_name}`  \n",
                f"**Current Schema Context**: `{schema_name}`  \n",
                f"**Default Volume**: `{volume_name}`\n",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 1. Volumes: Writing Files\n",
                "\n",
                "CompassX Volumes provide cloud-native, securable storage accessible via the `cx://` protocol.\n",
                "URL format: `cx://<catalog>.<schema>.<volume>/<file_path>`\n",
                "\n",
                "You can write tabular data directly using **pandas** or arbitrary text/binary files using **fsspec**.",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import pandas as pd\n",
                "import fsspec\n",
                "\n",
                "try:\n",
                "    import services.fsspec_cx\n",
                "except ImportError:\n",
                "    pass\n",
                "\n",
                f'CATALOG = "{catalog_name}"\n',
                f'SCHEMA = "{schema_name}"\n',
                f'VOLUME = "{volume_name}"\n',
                "\n",
                "# Sample tabular dataset\n",
                "data = {\n",
                '    "device_id": [101, 102, 103, 104],\n',
                '    "sensor_name": ["Solar Inverter A", "Solar Inverter B", "Battery Unit 1", "Grid Gateway"],\n',
                '    "efficiency_rate": [0.94, 0.98, 0.89, 0.96],\n',
                '    "status": ["active", "active", "maintenance", "active"],\n',
                "}\n",
                "df = pd.DataFrame(data)\n",
                "\n",
                "# -- Option A: Save DataFrame as CSV to Volume --\n",
                'csv_url = f"cx://{CATALOG}.{SCHEMA}.{VOLUME}/devices.csv"\n',
                "df.to_csv(csv_url, index=False)\n",
                'print(f"Successfully saved DataFrame to: {csv_url}")\n',
                "\n",
                "# -- Option B: Write raw text or binary data using fsspec --\n",
                'txt_url = f"cx://{CATALOG}.{SCHEMA}.{VOLUME}/readme.txt"\n',
                'with fsspec.open(txt_url, "w") as f:\n',
                '    f.write("Welcome to CompassX Volumes!\\nFiles written here are securely stored and catalog-governed.\\n")\n',
                'print(f"Successfully wrote text file to: {txt_url}")\n',
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 2. Volumes: Reading Files\n",
                "\n",
                "Files stored in Volumes can be read back using `pandas.read_csv`, `pandas.read_parquet`, or `fsspec.open`.",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# -- Option A: Read CSV directly into a pandas DataFrame --\n",
                "df_read = pd.read_csv(csv_url)\n",
                'print("DataFrame read from volume:")\n',
                "try:\n",
                "    display(df_read)\n",
                "except NameError:\n",
                "    print(df_read)\n",
                "\n",
                "# -- Option B: Read raw text file using fsspec --\n",
                'with fsspec.open(txt_url, "r") as f:\n',
                '    print("\\nRaw text read from volume:")\n',
                "    print(f.read())\n",
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 3. AI Agent Tools: Authoring & Promotion\n",
                "\n",
                "CompassX enables you to write Python functions, decorate them with `@cx.tool`, test them locally in your notebook, and **promote** them to the Unified Catalog so AI Agents can autonomously discover and invoke them.",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "try:\n",
                "    import compassx_tools as cx\n",
                "except ImportError:\n",
                "    from services import compassx_tools as cx\n",
                "\n",
                "# Define a tool with @cx.tool\n",
                "@cx.tool(\n",
                '    name="calculate_solar_power",\n',
                '    description="Calculate expected solar power output in Watts and Kilowatts given panel surface area and solar irradiance."\n',
                ")\n",
                "def calculate_solar_power(area_sqm: float, irradiance_wm2: float = 1000.0, efficiency: float = 0.20) -> dict:\n",
                '    """Calculate expected solar power output.\n',
                "    \n",
                "    Parameters:\n",
                "        area_sqm: Total panel surface area in square meters.\n",
                "        irradiance_wm2: Solar irradiance in W/m^2 (standard test condition is 1000 W/m^2).\n",
                "        efficiency: Panel conversion efficiency rate (e.g. 0.20 for 20%).\n",
                '    """\n',
                "    watts = round(area_sqm * irradiance_wm2 * efficiency, 2)\n",
                "    return {\n",
                '        "surface_area_sqm": area_sqm,\n',
                '        "irradiance_wm2": irradiance_wm2,\n',
                '        "efficiency_rate": efficiency,\n',
                '        "power_output_watts": watts,\n',
                '        "power_output_kw": round(watts / 1000.0, 3),\n',
                "    }\n",
                "\n",
                "# Test the tool locally in the notebook before promoting\n",
                "test_output = calculate_solar_power(area_sqm=30.0, irradiance_wm2=950.0)\n",
                'print("Local tool execution result:", test_output)\n',
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Promote the tool into your workspace catalog and schema\n",
                "# Once promoted, AI agents running workflows in this workspace can call this tool\n",
                "promoted_tool = cx.tools.promote(\n",
                "    calculate_solar_power,\n",
                "    catalog=CATALOG,\n",
                "    schema=SCHEMA,\n",
                ")\n",
                'print(f"Tool promoted successfully: {promoted_tool.full_name} (Version {promoted_tool.version})")\n',
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 4. Tables: Creating & Writing Catalog Tables (`cx.write_table`)\n",
                "\n",
                "CompassX allows you to create managed tables directly from pandas DataFrames using `cx.write_table` (or `df.write_table`).\n",
                "Tables written here are persisted in cloud object storage (Apache Iceberg format) and immediately registered in the **Unified Data Catalog**, making them visible in the catalog UI and queryable across all workspaces.\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import pandas as pd\n",
                "\n",
                "try:\n",
                "    import services.compassx_sql as cx\n",
                "except ImportError:\n",
                "    import compassx_sql as cx\n",
                "\n",
                "# Create dummy sample telemetry DataFrame\n",
                "telemetry_data = {\n",
                '    "device_id": [101, 102, 103, 104, 105],\n',
                '    "sensor_name": ["Solar Inverter A", "Solar Inverter B", "Battery Unit 1", "Grid Gateway", "Solar Inverter C"],\n',
                '    "efficiency_rate": [0.94, 0.98, 0.89, 0.96, 0.91],\n',
                '    "power_output_kw": [45.2, 52.8, 38.4, 60.1, 44.0],\n',
                '    "status": ["active", "active", "maintenance", "active", "active"],\n',
                "}\n",
                "df_telemetry = pd.DataFrame(telemetry_data)\n",
                "\n",
                "# Table name format: <catalog>.<schema>.<table>\n",
                'table_name = "device_metrics"\n',
                'table_ref = f"{CATALOG}.{SCHEMA}.{table_name}"\n',
                "\n",
                "# Write DataFrame and register as a table in the Unified Catalog\n",
                'res = cx.write_table(df_telemetry, table_ref, mode="overwrite")\n',
                'print(f"Table successfully registered in Catalog: {table_ref}")\n',
                'print(f"Engine: {res.get(\'engine\', \'iceberg\')} | Rows written: {res.get(\'rows_written\', len(df_telemetry))}")\n',
            ],
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 5. Tables: Querying Catalog Tables (`cx.sql`)\n",
                "\n",
                "You can execute standard SQL queries against any catalog table using `cx.sql`, returning results directly as a pandas DataFrame.\n",
            ],
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Query and read data from the registered Catalog table\n",
                'query_result = cx.sql(f"""\n',
                "    SELECT \n",
                "        device_id,\n",
                "        sensor_name,\n",
                "        power_output_kw,\n",
                "        efficiency_rate * 100.0 AS efficiency_pct,\n",
                "        status\n",
                f"    FROM {{table_ref}}\n",
                "    WHERE status = 'active'\n",
                "    ORDER BY power_output_kw DESC\n",
                '""")\n',
                "\n",
                'print(f"Query results from table \'{table_ref}\':")\n',
                "try:\n",
                "    display(query_result)\n",
                "except NameError:\n",
                "    print(query_result)\n",
            ],
        },
    ]

    return {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {
                "name": "python",
                "version": "3.11",
            },
        },
        "cells": cells,
    }
