{{- if and .Values.airflow.enabled .Values.airflow.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "compassx.airflowServiceAccountName" . }}
  labels:
    {{- include "compassx.labels" . | nindent 4 }}
    app.kubernetes.io/component: airflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "compassx.airflowFullname" . }}-role
  labels:
    {{- include "compassx.labels" . | nindent 4 }}
    app.kubernetes.io/component: airflow
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch", "create", "delete", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "compassx.airflowFullname" . }}-rolebinding
  labels:
    {{- include "compassx.labels" . | nindent 4 }}
    app.kubernetes.io/component: airflow
subjects:
  - kind: ServiceAccount
    name: {{ include "compassx.airflowServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "compassx.airflowFullname" . }}-role
{{- end }}
